"""edit_orders

Revision ID: 3d19dc76a7c4
Revises: dfa4992d87b1
Create Date: 2025-05-13 20:25:51.605264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d19dc76a7c4'
down_revision: Union[str, None] = 'dfa4992d87b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('reviewed_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_reviews_author_id_users', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_reviewed_id_users'), 'reviews', 'users', ['reviewed_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_reviewer_id_users'), 'reviews', 'users', ['reviewer_id'], ['id'])
    op.drop_column('reviews', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_reviews_reviewer_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_reviewed_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_author_id_users', 'reviews', 'users', ['author_id'], ['id'])
    op.drop_column('reviews', 'reviewed_id')
    op.drop_column('reviews', 'reviewer_id')
    # ### end Alembic commands ###
