"""fix_migration_holazsx

Revision ID: 48fb16459c98
Revises: 416d3acf91de
Create Date: 2025-05-15 16:13:56.889432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fb16459c98'
down_revision: Union[str, None] = '416d3acf91de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_order_statuses_name'))
    )
    op.create_table('orders',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.CheckConstraint('start_price >= 0', name=op.f('ck_orders_positive_price')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_orders_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_orders_category_id_categories')),
    sa.ForeignKeyConstraint(['status_id'], ['order_statuses.id'], name=op.f('fk_orders_status_id_order_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('reviews',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_valid_rating')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_reviews_file_id_files')),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], name=op.f('fk_reviews_reviewed_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_foreign_key(op.f('fk_chats_order_id_orders'), 'chats', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chats_order_id_orders'), 'chats', type_='foreignkey')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('order_statuses')
    op.drop_table('categories')
    # ### end Alembic commands ###
