"""
merge_holazsx

Revision ID: 7712444e3b3f
Revises: e4deb457cf45
Create Date: 2025-05-16 10:32:49.017219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7712444e3b3f'
down_revision: Union[str, None] = 'e4deb457cf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('message', sa.String(length=200), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
                    )
    op.create_table('bids',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='bidstatus'), nullable=True),
                    sa.CheckConstraint('price > 0', name=op.f('ck_bids_positive_price')),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_bids_order_id_orders')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bids_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('notifications')
    # ### end Alembic commands ###
