"""edit_orders

Revision ID: 7a5de1721879
Revises: eaf15c1d81b1
Create Date: 2025-05-13 20:42:31.950706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5de1721879'
down_revision: Union[str, None] = 'eaf15c1d81b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('reviews', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###
