"""empty message

Revision ID: ada036a4ea2d
Revises: 6b0d25f38127
Create Date: 2025-05-11 18:33:20.715914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada036a4ea2d'
down_revision: Union[str, None] = '6b0d25f38127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_order_statuses_name'))
    )
    op.create_table('order_user_association',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_user_association_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_order_user_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'order_id', name=op.f('pk_order_user_association'))
    )
    op.create_index('idx_order_user_unique', 'order_user_association', ['user_id', 'order_id', 'relation_type'], unique=True)
    op.create_table('chat_user_association',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_user_association_chat_id_chats')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_user_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name=op.f('pk_chat_user_association'))
    )
    op.create_index('idx_chat_user_unique', 'chat_user_association', ['user_id', 'chat_id'], unique=True)
    op.drop_table('offers')
    op.drop_table('order_attachments')
    op.drop_index('idx_chat_order', table_name='chats')
    op.drop_constraint('fk_files_author_id_users', 'files', type_='foreignkey')
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'size')
    op.drop_column('files', 'author_id')
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('orders', sa.Column('status_id', sa.Integer(), server_default='1', nullable=False))
    op.drop_index('idx_order_status', table_name='orders')
    op.create_foreign_key(op.f('fk_orders_status_id_order_statuses'), 'orders', 'order_statuses', ['status_id'], ['id'])
    op.drop_column('orders', 'status')
    op.drop_index('idx_review_author', table_name='reviews')
    op.drop_index('idx_review_executor', table_name='reviews')
    op.drop_index('idx_role_permission', table_name='role_permissions')
    op.drop_column('role_permissions', 'id')
    op.alter_column('roles', 'is_core',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'is_core',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('role_permissions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('idx_role_permission', 'role_permissions', ['role_id', 'permission'], unique=True)
    op.create_index('idx_review_executor', 'reviews', ['executor_id'], unique=False)
    op.create_index('idx_review_author', 'reviews', ['author_id'], unique=False)
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_orders_status_id_order_statuses'), 'orders', type_='foreignkey')
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.drop_column('orders', 'status_id')
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('files', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_files_author_id_users', 'files', 'users', ['author_id'], ['id'])
    op.create_index('idx_chat_order', 'chats', ['order_id'], unique=False)
    op.create_table('order_attachments',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='fk_order_attachments_file_id_files'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_attachments_order_id_orders'),
    sa.PrimaryKeyConstraint('id', name='pk_order_attachments')
    )
    op.create_table('offers',
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('price >= (0)::numeric', name='ck_offers_positive_offer_price'),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name='fk_offers_executor_id_users'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_offers_order_id_orders'),
    sa.PrimaryKeyConstraint('id', name='pk_offers')
    )
    op.drop_index('idx_chat_user_unique', table_name='chat_user_association')
    op.drop_table('chat_user_association')
    op.drop_index('idx_order_user_unique', table_name='order_user_association')
    op.drop_table('order_user_association')
    op.drop_table('order_statuses')
    # ### end Alembic commands ###
